// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC06pF8IlIRrkGsXmAQvSGJt4-lpbbH7iw',
    appId: '1:136739074452:web:ed0ab677de75cdd0559f81',
    messagingSenderId: '136739074452',
    projectId: 'nuitrite',
    authDomain: 'nuitrite.firebaseapp.com',
    storageBucket: 'nuitrite.firebasestorage.app',
    measurementId: 'G-ET1NCWSD6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqcF_7gEUIF2dxMF19rBofJDoA5kUmqVM',
    appId: '1:136739074452:android:b6f2cd48b6b2eb79559f81',
    messagingSenderId: '136739074452',
    projectId: 'nuitrite',
    storageBucket: 'nuitrite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBieTN8T63E_2GUvx7bXkZjh2t5g4urHcY',
    appId: '1:136739074452:ios:cb59f13c238c74f1559f81',
    messagingSenderId: '136739074452',
    projectId: 'nuitrite',
    storageBucket: 'nuitrite.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBieTN8T63E_2GUvx7bXkZjh2t5g4urHcY',
    appId: '1:136739074452:ios:cb59f13c238c74f1559f81',
    messagingSenderId: '136739074452',
    projectId: 'nuitrite',
    storageBucket: 'nuitrite.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC06pF8IlIRrkGsXmAQvSGJt4-lpbbH7iw',
    appId: '1:136739074452:web:8a4aa0fef68334fe559f81',
    messagingSenderId: '136739074452',
    projectId: 'nuitrite',
    authDomain: 'nuitrite.firebaseapp.com',
    storageBucket: 'nuitrite.firebasestorage.app',
    measurementId: 'G-CNKYN9MJ2Z',
  );
}
